### PR TITLE
Update debian control

### PR DESCRIPTION
**Pull request by bizicz**
Conflicts, Replaces, Provides:  added moosefs-* (new package name)

### CODE REVIEW

**Comment by onlyjob** [comment]
Let's not do this please. It is unnecessary.

**Comment by psarna** [comment]
@bizicz, can you explain why this change is necessary?
@onlyjob, can you explain why this change is unnecessary?

**Comment by onlyjob** [comment]
> What can be asserted without proof can be dismissed without proof.
        -- Christopher Hitchens, 2004

So it is on @bizicz to explain benefits of such change. ;)
It seems obvious that intent was to avoid conflicts with previously installed moosefs packages. However LizardFS packages are not a 100% drop-in replacement (hence at least `Provides` are wrong). MooseFS was never in Debian so essentially conflict with 3rd party packages is unnecessary. Debian users should always be careful with 3rd party packages from non-official repositories so it is on them to avoid installing conflicting packages from two different vendors at the same time. Don't count me in to actually test whether moosefs packages will be correctly taken over by LizardFS packages... ;)

Now when [LizardFS packages are officially in Debian](https://tracker.debian.org/pkg/lizardfs) this packaging became redundant. It is not helpful to maintain two different branches of Debian packaging...

**Comment by psarna** [comment]
Time's up. That's 1 reasonable argument for *no* and 0 arguments for *yes*, so the topic is closed.

**Pull request closed without merging**
