### PR TITLE
OSX and BSD compatibility

### PR DESCRIPTION
**Pull request by jedisct1**
This makes Lizardfs build on OSX.

- Use `pkg-config` in order to find the FUSE library and required flags. This make it work with multiple FUSE implementations, including OSXFUSE.
- Do not require `clock_gettime()`
- Add missing headers
- `le32toh()` and friends are glibc-specific. Define these macros if required.
- Format string fixes.

Tested on OSX 10.10. Tested for no regressions on Debian 7.8.

### CODE REVIEW

**Comment by jedisct1** [comment]
Can you take a look at this?

I'd like to get lizardfs into Homebrew and the OpenBSD ports collection, but these changes are required.

**Comment by jedisct1** [comment]
Ping? I've been rebasing this for the past 2 months.

**Comment by Zorlin** [comment]
+1 - this is somewhat important if we want to stay multi-platform.

**Comment by onlyjob** [comment]
Even if it means supporting legacy platforms... ;)

**Comment by onlyjob** [comment]
I also think that it is very important to improve speed of pull requests' review.

**Comment by Zorlin** [comment]
@onlyjob Agreed.

**Comment by psarna** [comment]
This pull request is under review, but it is very time consuming.
For reference:

http://cr.skytechnology.pl:8081/#/c/1559/
http://cr.skytechnology.pl:8081/#/c/1560/
http://cr.skytechnology.pl:8081/#/c/1561/
http://cr.skytechnology.pl:8081/#/c/1562/
http://cr.skytechnology.pl:8081/#/c/1563/
http://cr.skytechnology.pl:8081/#/c/1564/
http://cr.skytechnology.pl:8081/#/c/1565/
http://cr.skytechnology.pl:8081/#/c/1566/
http://cr.skytechnology.pl:8081/#/c/1567/
http://cr.skytechnology.pl:8081/#/c/1568/
http://cr.skytechnology.pl:8081/#/c/1569/
http://cr.skytechnology.pl:8081/#/c/1570/
http://cr.skytechnology.pl:8081/#/c/1571/
http://cr.skytechnology.pl:8081/#/c/1572/
http://cr.skytechnology.pl:8081/#/c/1573/
http://cr.skytechnology.pl:8081/#/c/1551/


There are several reasons why the progress is slow:
* The initial set of 16 commits above caused issues with building LizardFS on virtually every platform we support, including OSX - and these are not trivial to fix properly
* Hardly any commit referenced above conforms to submitting rules: https://github.com/lizardfs/lizardfs/wiki/Submitting-Patches
* This pull request contains non-intuitive workarounds that we wish to avoid - and finding all of them along with their proper solutions is time-consuming
* We require that each contribution passes all tests, and with so many changes it takes many iterations to get rid of all issues

**Comment by Zorlin** [comment]
Bravo for the transparency! :)

**Comment by psarna** [comment]
There, merged.

**Comment by jedisct1** [comment]
Dancing

**Pull request closed without merging**
