### PR TITLE
FindFUSE.cmake: Support for systems which use librefuse.

### PR DESCRIPTION
**Pull request by christiank**
This includes NetBSD, at a minimum.

Getting LizardFS to _actually work_ on NetBSD, however, requires some extra changes -- you can follow the progress [here](https://wip.pkgsrc.org/cgi-bin/gitweb.cgi?p=pkgsrc-wip.git;a=tree;f=lizardfs;hb=refs/heads/master)

### CODE REVIEW

**Comment by 4Dolio** [comment]
Playing my ingorance card. How if at all does this relate or is it applicable to other BSDs like FreeBSD or OpenBSD? ... I miss LizardFS not being readily available for FreeBSD like MooseFS was and still is... :(

**Comment by christiank** [comment]
At this point, `librefuse` is basically only a NetBSD thing. But I thought I saw somewhere LizardFS was already working on FreeBSD? o_O  Maybe I got confused.

The goal with this patch, though, is simply to be aware that sometimes the library which implements FUSE is called `librefuse.so`, not `libfuse.so`.

**Comment by 4Dolio** [comment]
Thanks for the NetBSD work and clarification. Sorry for the extra noise on this thread. Yes I have also seen that FreeBSD is supported but having not attempted since 2.6 im not sure just how far that support goes exactly...

**Comment by pbeza** [comment]
Has anyone tried to compile LizardFS `3.13` or `3.12` on NetBSD?

**Comment by pbeza** [comment]
I'm not familiar with NetBSD, so followed [this tutorial][1] to familiarize myself with installing packages on NetBSD (I'm using [this repository][2]).

I tried to compile LizardFS on [NetBSD][3] and I have hard time to install all of the dependencies, specifically:
  - _BerkeleyDB_: I installed it with `pkg_add db5` but it is not found by `cmake ..`
  - _ISAL_: I can't find package for NetBSD
  - _PAM_: I can't find package for NetBSD

Those 3 packages were troublesome for me so I temporarily commented out them from [`cmake/Libraries.cmake`][4]. After commenting them out `cmake ..` completed successfully. Fuse was found in `/usr/pkg/lib/libfuse.so` as you can see in the screenshot below.

Screenshot from 2019-07-23 13-14-02

Here is full compilation on NetBSD:
compilation

Here is NetBSD version that I was using to test LizardFS compilation:

Screenshot from 2019-07-23 13-25-30

As you can see, _I can't confirm your problem_ (maybe it used to be a problem on old NetBSD?). Please clarify and reopen the issue if I'm wrong.

[1]: http://www.linuxfromscratch.org/lfs/view/stable/chapter06/pkgmgt.html
[2]: http://cdn.netbsd.org/pub/pkgsrc/packages/NetBSD/amd64/8.1/All/
[3]: https://en.wikipedia.org/wiki/NetBSD
[4]: https://github.com/lizardfs/lizardfs/blob/master/cmake/Libraries.cmake

**Pull request closed without merging**
