### PR TITLE
build: Fix FTBFS on kfreebsd-any, powerpc, ppc64 and s390x.

### PR DESCRIPTION
**Pull request by onlyjob**
Closes: #352, #354, #363.

### CODE REVIEW

**Comment by psarna** [comment]
Can you verify if everything still builds fine with http://cr.skytechnology.pl:8081/#/c/2315/ after an amendment?

**Comment by onlyjob** [comment]
That would be difficult... I just don't have time for that now... :(  Please remember that `check_include_files` is also called from `Libraries.cmake` as introduced by #359.

If I understand your amendment, it moved `include(CheckIncludeFiles)` from `Libraries.cmake` to `CheckIncludes.cmake`? Could you be more specific regarding amendments next time please?

Probably it won't hurt to introduce `include(CheckIncludeFiles)` to both files.
As committed my changes fixed build on all architectures...

**Comment by onlyjob** [comment]
@psarna, c2315 amendment is great -- it fixes the problem and do not break #359. Please commit.

**Comment by onlyjob** [comment]
Only one FTBFS left to fix: #354 / cc33e8f (fix is similar to [iperf@738c4dc](https://github.com/esnet/iperf/commit/738c4dc68f3355a0133f8de79ff2340e47b65f91#diff-4635044f740fdd22ae452de5c5bb9570)).

**Comment by onlyjob** [comment]
Ping?

**Comment by onlyjob** [comment]
Well??

**Comment by psarna** [comment]
Your fix had to be slightly amended, can you verify if all FTBFS are still gone?
http://cr.skytechnology.pl:8081/#/c/2370/

**Comment by onlyjob** [comment]
It is perfect: with your correction it is much better than my original patch. ;)
FTBFS on kFreeBSD is fixed -- please commit.

**Comment by onlyjob** [comment]
All merged, thanks!

**Pull request closed without merging**
