### PR TITLE
cgiserv: removed buggy redundant PID file management code:

### LINKED ISSUE #215: cgiserv: PID file issues
#### Assumes that PID file is writeable

`mfscgiserv` fails to start in a very bad way if it can not write its PID/lock file -- it just hangs and do not exit with error code:

~~~~
Traceback (most recent call last):
  File "/usr/sbin/mfscgiserv", line 492, in <module>
    if wdlock(lockfname,mode,locktimeout)==1:
  File "/usr/sbin/mfscgiserv", line 394, in wdlock
    l = mylock(fname)
  File "/usr/sbin/mfscgiserv", line 372, in mylock
    fd = posix.open(filename,posix.O_RDWR|posix.O_CREAT,0666)
OSError: [Errno 13] Permission denied: '/var/lib/lizardfs/.mfscgiserv.lock'
~~~~

#### PID/lock file left behind after exit 

`mfscgiserv` do not remove its PID/lock file `.mfscgiserv.lock` which is left behind in `/var/lib/lizardfs` after termination.

#### PID/lock file name issues

`.mfscgiserv.lock` file contains PID of a process. Why is it called `.lock`?

Traditionally

 * PID files should be in `/var/run`.
 * should not be hidden (i.e. no '.' (dot) in the beginning of file name).

Perhaps it would be best to implement a command line option to specify path to PID file.

Thanks.

### PR DESCRIPTION
**Pull request by onlyjob**
Removing this code fixes #215 and allows to run cgiserv as "nobody".

 When cgiserv started directly PID management is unnecessary;

 When cgiserv started by service manager PID management is in the way of
 starting as different user.

Please note that stop/restart "features" are to be removed as per #218.

Please review.

Signed-off-by: Dmitry Smirnov <onlyjob@member.fsf.org>

### CODE REVIEW

**Comment by marcinsulikowski** [comment]
@onlyjob We are going to solve the problem in the following change: http://cr.skytechnology.pl:8081/#/c/1388 (it's undergoing a review in our Gerrit). This commit contains your init script for Debian and Ubuntu OS-es.

**Comment by Zorlin** [comment]
Marcin,

That is excellent news. Thank you for taking outside contributions
seriously.

~ Benjamin

**Comment by marcinsulikowski** [comment]
@onlyjob We have a question about the following part of your `lizardfs-cgiserv.init` script:
```sh
# Read configuration variable file if it is present
DEFAULTS_FILE=/etc/default/${NAME}
[ -r "$DEFAULTS_FILE" ] && . $DEFAULTS_FILE

PIDF=/var/run/${NAME}.pid
RETRY=TERM/30/KILL/5
```

Why the order is like this? Shouldn't we define those variables before reading the `$DEFAULTS_FILE`?

**Comment by onlyjob** [comment]
@marcinsulikowski, I reckon it's not too important but I did not want to let user(s) mess with the location of a PID file. It is better to keep things more or less standard. As for RETRY I also doubt it should be configurable...

**Comment by marcinsulikowski** [comment]
@onlyjob I have questions about the following:
```sh
        if R=$(start-stop-daemon --stop --exec $EXEC --pidfile ${PIDF} --remove-pidfile \
            --retry=$RETRY --quiet);
```
The first is: does `start-stop-daemon` print error messages to stdout or stderr? Isn't `2>&1` missing here?

The next one. We have been testing this init script on Ubuntu 12.04 and `start-stop-daemon` doesn't support `--remove-pidfile` there (the same on Ubuntu 14.04). For example `/etc/init.d/rsync` uses:
```sh
  stop)
	log_daemon_msg "Stopping rsync daemon" "rsync"
	start-stop-daemon --stop --quiet --oknodo --pidfile $RSYNC_PID_FILE
	log_end_msg $?
	rm -f $RSYNC_PID_FILE
	;;

```
Should we use different init scripts for distributions without support for `--remove-pidfile` or is it OK to use `rm` in all scripts (for Debian and Ubuntu) like in rsync's script?

**Comment by onlyjob** [comment]
As far as I remember when stopping service I'm deliberately discarding STRERR to avoid printing confusing messages when daemon is not running etc. I did some testing and decided that it is better this way...

I have nothing against using `rm` if Ubuntu needs it... (Bloody Ubuntu, always needs workarounds... :( )
I hope soon you won't have to worry about it as once Debian package is ready they will just snatch it from us...

**Pull request closed without merging**
