### PR TITLE
codespell: spelling corrections

### PR DESCRIPTION
**Pull request by onlyjob**
Signed-off-by: Dmitry Smirnov <onlyjob@member.fsf.org>

### CODE REVIEW

**Comment by Zorlin** [comment]
src/mount/lizard_client.cc

Should be "happen", not "happened".

**Comment by Zorlin** [comment]
Otherwise, looks good to me

**Comment by onlyjob** [comment]
Well spotted, Benjamin. Thanks. Corrected.

**Comment by onlyjob** [comment]
Thanks! :)

**Pull request closed without merging**
