### PR TITLE
main: Systemd notification for service start-up completion (Closes: #340).

### PR DESCRIPTION
**Pull request by onlyjob**
Please review.

Signed-off-by: Dmitry Smirnov <onlyjob@member.fsf.org>

### CODE REVIEW

**Comment by onlyjob** [comment]
Just updated commit to add missing space after daemon name in status message.

**Comment by onlyjob** [comment]
A week passed... How is the progress? I see that http://cr.skytechnology.pl:8081/#/c/2313/ is in "Cannot Merge" status so I rebased my pull request.

**Comment by psarna** [comment]
Don't worry about "Cannot Merge" status, it is an internal gerrit thing and its not directly related to your github repository at all. I assume that both of your commits will be merged by the end of the day.

**Comment by onlyjob** [comment]
Thanks :smiley:

**Comment by onlyjob** [comment]
Committed as 2bf24c8.

**Pull request closed without merging**
