### PR TITLE
Systemd updates and improvements

### PR DESCRIPTION
**Pull request by onlyjob**

### CODE REVIEW

**Comment by onlyjob** [comment]
Rebased.

**Comment by onlyjob** [comment]
Ping?

**Comment by richard-scott** [comment]
Other cluster file systems use this in all their .service files:

```
Wants=network-online.target
After=network.target network-online.target
```
perhaps you use that?

**Comment by onlyjob** [comment]
Just curious, what other cluster file systems?
For now I'd leave `network-online.target` for later because I did not test this configuration yet.
There always can be another pull request once this one is merged, if ever. :)

**Comment by richard-scott** [comment]
um.. I checked what MooseFS are doing in their "current" (not stable) release :-)

**Comment by onlyjob** [comment]
Another week passed... Do I need to make any changes? IMHO this is safe enough to merge.

**Comment by onlyjob** [comment]
Another week and the half passed...

**Comment by psarna** [comment]
ffc52fa4b09bcbd86bc06b5b6882ec11ecd5cdcf
6fda7494183c441dab048d97ebc12f788f3cb8f8

**Comment by onlyjob** [comment]
Lovely! Thanks, Piotr. A little bit more and it would be a year since this pull request was opened. Nice that we were able to close it, at last. :)

**Pull request closed without merging**
